function y = filterHighPass(x)
%FILTERHIGHPASS Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 11-Aug-2018 23:35:55

persistent Hd;

if isempty(Hd)
    
    Fstop = 0.001;  % Stopband Frequency
    Fpass = 0.01;   % Passband Frequency
    Astop = 60;     % Stopband Attenuation (dB)
    Apass = 1;      % Passband Ripple (dB)
    
    h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass);
    
    Hd = design(h, 'equiripple', ...
        'MinOrder', 'any', ...
        'StopbandShape', 'flat');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


